### PR TITLE
Add logstatter as dependency and upload logstatter cookbook in configure leader

### PR DESCRIPTION
**Pull request by malvads**
- Add logstatter dependency

### CODE REVIEW

**Comment by malvads** [comment]
We need to resolve the conflict before merging @manegron

**Comment by malvads** [comment]
I fixed the conflict

**Comment by manegron** [comment]
you are missing the cookbook of rblogstatter in the listCookbooks of rb_configure_leader.sh script

`Dec 15 15:56:45 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[15590]: ######################################################################################################
Dec 15 15:56:45 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[15590]: #  Uploading cookbooks
Dec 15 15:56:45 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[15590]: ######################################################################################################
Dec 15 15:56:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[15590]: 
Dec 15 15:56:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35963]: Uploading rb-selinux   [0.0.1]
Dec 15 15:56:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35963]: Uploaded 1 cookbook.
Dec 15 15:56:48 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35977]: Uploading cron           [1.7.6]
Dec 15 15:56:49 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35977]: Uploaded 1 cookbook.
Dec 15 15:56:51 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35988]: Uploading zookeeper      [1.0.3]
Dec 15 15:56:51 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35988]: Uploaded 1 cookbook.
Dec 15 15:56:52 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36005]: Uploading kafka          [1.0.7]
Dec 15 15:56:53 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36005]: Uploaded 1 cookbook.
Dec 15 15:56:54 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36016]: Uploading druid          [1.4.5]
Dec 15 15:56:55 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36016]: Uploaded 1 cookbook.
Dec 15 15:56:57 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36027]: Uploading http2k         [1.0.7]
Dec 15 15:56:57 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36027]: Uploaded 1 cookbook.
Dec 15 15:56:58 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36039]: Uploading memcached      [1.0.3]
Dec 15 15:56:59 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36039]: Uploaded 1 cookbook.
Dec 15 15:57:01 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36050]: Uploading chef-server    [1.0.6]
Dec 15 15:57:01 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36050]: Uploaded 1 cookbook.
Dec 15 15:57:03 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36071]: Uploading consul         [1.0.7]
Dec 15 15:57:03 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36071]: Uploaded 1 cookbook.
Dec 15 15:57:04 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36083]: Uploading hadoop         [1.0.0]
Dec 15 15:57:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36083]: Uploaded 1 cookbook.
Dec 15 15:57:07 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36096]: Uploading samza          [0.0.1]
Dec 15 15:57:07 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36096]: Uploaded 1 cookbook.
Dec 15 15:57:09 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36107]: Uploading nginx          [0.0.6]
Dec 15 15:57:09 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36107]: Uploaded 1 cookbook.
Dec 15 15:57:11 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36118]: Uploading geoip          [0.0.2]
Dec 15 15:57:11 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36118]: Uploaded 1 cookbook.
Dec 15 15:57:13 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36134]: Uploading webui          [0.1.5]
Dec 15 15:57:13 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36134]: Uploaded 1 cookbook.
Dec 15 15:57:17 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36145]: Uploading snmp           [0.1.2]
Dec 15 15:57:17 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36145]: Uploaded 1 cookbook.
Dec 15 15:57:18 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36158]: Uploading mongodb        [0.0.4]
Dec 15 15:57:19 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36158]: Uploaded 1 cookbook.
Dec 15 15:57:20 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36169]: Uploading rbmonitor      [0.0.2]
Dec 15 15:57:20 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36169]: Uploaded 1 cookbook.
Dec 15 15:57:22 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36180]: Uploading rbscanner      [0.0.2]
Dec 15 15:57:22 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36180]: Uploaded 1 cookbook.
Dec 15 15:57:24 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36196]: Uploading f2k            [0.0.8]
Dec 15 15:57:24 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36196]: Uploaded 1 cookbook.
Dec 15 15:57:26 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36207]: Uploading logstash       [1.0.22]
Dec 15 15:57:27 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36207]: Uploaded 1 cookbook.
Dec 15 15:57:28 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36220]: Uploading pmacct         [0.0.3]
Dec 15 15:57:29 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36220]: Uploaded 1 cookbook.
Dec 15 15:57:30 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36231]: Uploading minio          [0.0.3]
Dec 15 15:57:30 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36231]: Uploaded 1 cookbook.
Dec 15 15:57:32 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36242]: Uploading postgresql     [0.1.7]
Dec 15 15:57:32 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36242]: Uploaded 1 cookbook.
Dec 15 15:57:34 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36258]: Uploading rbdswatcher    [0.0.5]
Dec 15 15:57:34 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36258]: Uploaded 1 cookbook.
Dec 15 15:57:36 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36269]: Uploading rbevents-counter [0.0.6]
Dec 15 15:57:36 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36269]: Uploaded 1 cookbook.
Dec 15 15:57:38 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36281]: Uploading rsyslog        [1.0.5]
Dec 15 15:57:39 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36281]: Uploaded 1 cookbook.
Dec 15 15:57:40 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36293]: Uploading freeradius     [0.0.4]
Dec 15 15:57:41 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36293]: Uploaded 1 cookbook.
Dec 15 15:57:42 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36304]: Uploading rbnmsp         [0.0.6]
Dec 15 15:57:42 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36304]: Uploaded 1 cookbook.
Dec 15 15:57:44 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36320]: Uploading n2klocd        [0.0.2]
Dec 15 15:57:44 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36320]: Uploaded 1 cookbook.
Dec 15 15:57:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36331]: Uploading rbale          [0.0.2]
Dec 15 15:57:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36331]: Uploaded 1 cookbook.
Dec 15 15:57:49 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36343]: Uploading rbcep          [0.0.1]
Dec 15 15:57:49 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36343]: Uploaded 1 cookbook.
Dec 15 15:57:50 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36354]: Uploading k2http         [0.0.2]
Dec 15 15:57:51 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36354]: Uploaded 1 cookbook.
Dec 15 15:57:52 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36366]: Uploading rbcgroup       [0.0.1]
Dec 15 15:57:53 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36366]: Uploaded 1 cookbook.
Dec 15 15:57:54 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36382]: Uploading rb-proxy       [0.1.1]
Dec 15 15:57:55 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36382]: Uploaded 1 cookbook.
Dec 15 15:57:57 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36393]: Uploading snort          [0.0.9]
Dec 15 15:57:58 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36393]: Uploaded 1 cookbook.
Dec 15 15:58:00 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36405]: Uploading barnyard2      [0.0.4]
Dec 15 15:58:00 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36405]: Uploaded 1 cookbook.
Dec 15 15:58:01 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36416]: Uploading rb-ips         [0.1.4]
Dec 15 15:58:02 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36416]: Uploaded 1 cookbook.
Dec 15 15:58:04 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36433]: Uploading rbaioutliers   [0.0.1]
Dec 15 15:58:04 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36433]: Uploaded 1 cookbook.
Dec 15 15:58:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36444]: Uploading rb-manager     [1.6.2]
Dec 15 15:58:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36444]: ERROR: Cookbook rb-manager depends on cookbooks which are not currently
Dec 15 15:58:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36444]: ERROR: being uploaded and cannot be found on the server.
Dec 15 15:58:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36444]: ERROR: The missing cookbook(s) are: 'rblogstatter' version '>= 0.0.0'
`

**Comment by malvads** [comment]
> you are missing the cookbook of rblogstatter in the listCookbooks of rb_configure_leader.sh script
> 
> `Dec 15 15:56:45 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[15590]: ###################################################################################################### Dec 15 15:56:45 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[15590]: # Uploading cookbooks Dec 15 15:56:45 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[15590]: ###################################################################################################### Dec 15 15:56:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[15590]: Dec 15 15:56:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35963]: Uploading rb-selinux [0.0.1] Dec 15 15:56:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35963]: Uploaded 1 cookbook. Dec 15 15:56:48 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35977]: Uploading cron [1.7.6] Dec 15 15:56:49 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35977]: Uploaded 1 cookbook. Dec 15 15:56:51 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35988]: Uploading zookeeper [1.0.3] Dec 15 15:56:51 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[35988]: Uploaded 1 cookbook. Dec 15 15:56:52 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36005]: Uploading kafka [1.0.7] Dec 15 15:56:53 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36005]: Uploaded 1 cookbook. Dec 15 15:56:54 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36016]: Uploading druid [1.4.5] Dec 15 15:56:55 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36016]: Uploaded 1 cookbook. Dec 15 15:56:57 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36027]: Uploading http2k [1.0.7] Dec 15 15:56:57 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36027]: Uploaded 1 cookbook. Dec 15 15:56:58 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36039]: Uploading memcached [1.0.3] Dec 15 15:56:59 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36039]: Uploaded 1 cookbook. Dec 15 15:57:01 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36050]: Uploading chef-server [1.0.6] Dec 15 15:57:01 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36050]: Uploaded 1 cookbook. Dec 15 15:57:03 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36071]: Uploading consul [1.0.7] Dec 15 15:57:03 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36071]: Uploaded 1 cookbook. Dec 15 15:57:04 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36083]: Uploading hadoop [1.0.0] Dec 15 15:57:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36083]: Uploaded 1 cookbook. Dec 15 15:57:07 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36096]: Uploading samza [0.0.1] Dec 15 15:57:07 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36096]: Uploaded 1 cookbook. Dec 15 15:57:09 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36107]: Uploading nginx [0.0.6] Dec 15 15:57:09 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36107]: Uploaded 1 cookbook. Dec 15 15:57:11 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36118]: Uploading geoip [0.0.2] Dec 15 15:57:11 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36118]: Uploaded 1 cookbook. Dec 15 15:57:13 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36134]: Uploading webui [0.1.5] Dec 15 15:57:13 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36134]: Uploaded 1 cookbook. Dec 15 15:57:17 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36145]: Uploading snmp [0.1.2] Dec 15 15:57:17 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36145]: Uploaded 1 cookbook. Dec 15 15:57:18 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36158]: Uploading mongodb [0.0.4] Dec 15 15:57:19 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36158]: Uploaded 1 cookbook. Dec 15 15:57:20 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36169]: Uploading rbmonitor [0.0.2] Dec 15 15:57:20 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36169]: Uploaded 1 cookbook. Dec 15 15:57:22 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36180]: Uploading rbscanner [0.0.2] Dec 15 15:57:22 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36180]: Uploaded 1 cookbook. Dec 15 15:57:24 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36196]: Uploading f2k [0.0.8] Dec 15 15:57:24 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36196]: Uploaded 1 cookbook. Dec 15 15:57:26 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36207]: Uploading logstash [1.0.22] Dec 15 15:57:27 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36207]: Uploaded 1 cookbook. Dec 15 15:57:28 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36220]: Uploading pmacct [0.0.3] Dec 15 15:57:29 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36220]: Uploaded 1 cookbook. Dec 15 15:57:30 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36231]: Uploading minio [0.0.3] Dec 15 15:57:30 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36231]: Uploaded 1 cookbook. Dec 15 15:57:32 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36242]: Uploading postgresql [0.1.7] Dec 15 15:57:32 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36242]: Uploaded 1 cookbook. Dec 15 15:57:34 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36258]: Uploading rbdswatcher [0.0.5] Dec 15 15:57:34 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36258]: Uploaded 1 cookbook. Dec 15 15:57:36 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36269]: Uploading rbevents-counter [0.0.6] Dec 15 15:57:36 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36269]: Uploaded 1 cookbook. Dec 15 15:57:38 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36281]: Uploading rsyslog [1.0.5] Dec 15 15:57:39 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36281]: Uploaded 1 cookbook. Dec 15 15:57:40 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36293]: Uploading freeradius [0.0.4] Dec 15 15:57:41 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36293]: Uploaded 1 cookbook. Dec 15 15:57:42 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36304]: Uploading rbnmsp [0.0.6] Dec 15 15:57:42 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36304]: Uploaded 1 cookbook. Dec 15 15:57:44 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36320]: Uploading n2klocd [0.0.2] Dec 15 15:57:44 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36320]: Uploaded 1 cookbook. Dec 15 15:57:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36331]: Uploading rbale [0.0.2] Dec 15 15:57:47 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36331]: Uploaded 1 cookbook. Dec 15 15:57:49 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36343]: Uploading rbcep [0.0.1] Dec 15 15:57:49 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36343]: Uploaded 1 cookbook. Dec 15 15:57:50 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36354]: Uploading k2http [0.0.2] Dec 15 15:57:51 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36354]: Uploaded 1 cookbook. Dec 15 15:57:52 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36366]: Uploading rbcgroup [0.0.1] Dec 15 15:57:53 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36366]: Uploaded 1 cookbook. Dec 15 15:57:54 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36382]: Uploading rb-proxy [0.1.1] Dec 15 15:57:55 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36382]: Uploaded 1 cookbook. Dec 15 15:57:57 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36393]: Uploading snort [0.0.9] Dec 15 15:57:58 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36393]: Uploaded 1 cookbook. Dec 15 15:58:00 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36405]: Uploading barnyard2 [0.0.4] Dec 15 15:58:00 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36405]: Uploaded 1 cookbook. Dec 15 15:58:01 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36416]: Uploading rb-ips [0.1.4] Dec 15 15:58:02 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36416]: Uploaded 1 cookbook. Dec 15 15:58:04 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36433]: Uploading rbaioutliers [0.0.1] Dec 15 15:58:04 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36433]: Uploaded 1 cookbook. Dec 15 15:58:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36444]: Uploading rb-manager [1.6.2] Dec 15 15:58:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36444]: ERROR: Cookbook rb-manager depends on cookbooks which are not currently Dec 15 15:58:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36444]: ERROR: being uploaded and cannot be found on the server. Dec 15 15:58:06 rb-jz86w131dy.redborder.cluster rb_bootstrap.sh[36444]: ERROR: The missing cookbook(s) are: 'rblogstatter' version '>= 0.0.0' `

The merge overrided the changes: 

```https://github.com/redBorder/redborder-manager/pull/106/commits/4e477376fd4ea0fadbdc0844a4b45f0baa99aec4```

**Comment by malvads** [comment]
I added the cookbook

**Pull request merged**
